export interface BuiltInMcp {
  id: string
  name: string
  displayName: string
  description: string
  category: 'docs_storage' | 'collaboration' | 'research' | 'creative_core' | 'scene_reality' | 'publishing' | 'finance' | 'legal' | 'dev_tools' | 'marketing' | 'health' | 'travel'
  provider: string
  icon: string
  iconImage?: string
  bgColor: string
  textColor: string
  authMode: 'oauth' | 'api_key' | 'none'
  loginUrl?: string
  docsUrl?: string
  priority: 'S' | 'A' | 'B' | 'C'
  status: 'available' | 'beta' | 'coming_soon'
  toolsPreview: Array<{ name: string; description: string }>
}

const MCP_CATALOG_CANDIDATES: BuiltInMcp[] = [
  // ===== 金融/股票 =====
  {
    id: 'tongdaxin',
    name: '通达信',
    displayName: '通达信',
    description: '通过通达信 MCP 查询全球股票行情数据、条件选股、研究报告、公告资讯和宏观信息。支持个股基本面分析、同行业对比和智能选股筛查。',
    category: 'finance',
    provider: '通达信',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#dc2626',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://www.tdx.com.cn/',
    docsUrl: 'https://www.tdx.com.cn/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'stock_quote', description: '查询股票实时行情' },
      { name: 'stock_screen', description: '条件选股' },
      { name: 'research_report', description: '研究报告查询' },
    ]
  },
  {
    id: 'tencent_zixuan',
    name: '腾讯自选股',
    displayName: '腾讯自选股',
    description: '直连腾讯自选股，实时掌握毫秒级行情与资金动态，用自然语言分析自选数据、设置股价提醒、管理模拟交易，轻松搞定盯盘与投资决策。',
    category: 'finance',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#dc2626',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://stockapp.finance.qq.com/',
    docsUrl: 'https://stockapp.finance.qq.com/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'portfolio_query', description: '查询自选股' },
      { name: 'price_alert', description: '设置股价提醒' },
      { name: 'simulate_trade', description: '模拟交易' },
    ]
  },
  {
    id: 'hengshengyuan',
    name: '恒生聚源',
    displayName: '恒生聚源 MCP',
    description: '连接恒生聚源 MCP，查询金融结构化数据、研究报告、公司公告、新闻资讯、条件选股、宏观行业。支持基金经理观点持仓一致性分析、行业速报生成、金融资讯热点解读。',
    category: 'finance',
    provider: '恒生聚源',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.gildata.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'financial_data', description: '金融结构化数据查询' },
      { name: 'research_search', description: '研究报告搜索' },
      { name: 'announcement_query', description: '公司公告查询' },
    ]
  },

  // ===== 邮箱 =====
  {
    id: 'qq_mail',
    name: 'QQ邮箱',
    displayName: 'QQ邮箱',
    description: '收发、搜索和整理 QQ 邮件。用自然语言读取邮件内容、汇总邮件线程、管理文件夹。',
    category: 'collaboration',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#f97316',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://wx.mail.qq.com/',
    docsUrl: 'https://service.mail.qq.com/',
    priority: 'S',
    status: 'available',
    toolsPreview: [
      { name: 'list_emails', description: '列出邮件' },
      { name: 'send_email', description: '发送邮件' },
      { name: 'search_email', description: '搜索邮件' },
    ]
  },
  {
    id: 'netease_mail',
    name: '网易邮箱',
    displayName: '网易邮箱',
    description: '通过 IMAP/SMTP 连接邮箱，支持收发邮件、搜索、附件下载。支持 163、126、yeah.net 等网易邮箱及其他标准 IMAP/SMTP 邮箱。',
    category: 'collaboration',
    provider: '网易',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#dc2626',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://mail.163.com/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'list_emails', description: '列出邮件' },
      { name: 'send_email', description: '发送邮件' },
      { name: 'download_attachment', description: '下载附件' },
    ]
  },

  // ===== 知识库/文档 =====
  {
    id: 'ima_kb',
    name: 'ima知识库',
    displayName: 'ima知识库',
    description: '引用知识库资料及文件，浏览知识库详情。',
    category: 'docs_storage',
    provider: 'ima',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#22c55e',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://ima.qq.com/',
    docsUrl: 'https://ima.qq.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'search_knowledge', description: '搜索知识库' },
      { name: 'list_files', description: '列出文件' },
    ]
  },
  {
    id: 'lexiang_kb',
    name: '乐享知识库',
    displayName: '乐享知识库',
    description: '搜索、创建和管理乐享知识库中的文档。支持导入 Markdown、按标签整理内容、追踪团队文档的更新动态。',
    category: 'docs_storage',
    provider: '腾讯乐享',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#3b82f6',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://lexiangla.com/',
    docsUrl: 'https://lexiangla.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'search_doc', description: '搜索文档' },
      { name: 'create_doc', description: '创建文档' },
      { name: 'list_updates', description: '追踪更新' },
    ]
  },
  {
    id: 'tencent_docs',
    name: '腾讯文档',
    displayName: '腾讯文档',
    description: '创建、编辑和协作腾讯文档。用自然语言管理在线表格、文档和幻灯片，轻松完成内容查询、数据整理和团队协同。',
    category: 'collaboration',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/tencent-docs.jpg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://docs.qq.com/',
    docsUrl: 'https://docs.qq.com/',
    priority: 'S',
    status: 'available',
    toolsPreview: [
      { name: 'create_doc', description: '创建文档' },
      { name: 'edit_doc', description: '编辑文档' },
      { name: 'query_sheet', description: '查询表格数据' },
    ]
  },
  {
    id: 'feishu',
    name: '飞书',
    displayName: '飞书',
    description: '通过命令行管理飞书/Lark 全产品能力：即时通讯、邮箱、日历、云文档、电子表格、多维表格（Base）、幻灯片、画板、知识库、云空间、妙记、视频会议、任务、审批、考勤、通讯录。',
    category: 'collaboration',
    provider: '飞书',
    icon: 'connector',
    iconImage: '/connector-icons/feishu.jpg',
    bgColor: '#3370ff',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://open.feishu.cn/',
    docsUrl: 'https://open.feishu.cn/',
    priority: 'S',
    status: 'available',
    toolsPreview: [
      { name: 'send_message', description: '发送消息' },
      { name: 'create_doc', description: '创建文档' },
      { name: 'calendar_event', description: '日程管理' },
    ]
  },
  {
    id: 'dingtalk',
    name: '钉钉',
    displayName: '钉钉',
    description: '通过命令行管理钉钉全产品能力：AI 表格、考勤、日历、群聊与机器人、通讯录、开放平台文档、DING 消息、钉钉文档、钉钉云盘、AI 听记、邮箱、OA 审批、日志、待办。',
    category: 'collaboration',
    provider: '钉钉',
    icon: 'connector',
    iconImage: '/connector-icons/dingtalk.png',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://open.dingtalk.com/',
    docsUrl: 'https://open.dingtalk.com/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'send_message', description: '发送消息' },
      { name: 'create_doc', description: '创建文档' },
      { name: 'attendance_query', description: '考勤查询' },
    ]
  },
  {
    id: 'wps_docs',
    name: '金山文档',
    displayName: '金山文档',
    description: '创建、搜索和管理金山文档（WPS 云文档）。支持新建多种文档类型（Word/Excel/PDF/PPT/智能表格/多维表格/智能文档）、读取与搜索文档内容、编辑更新、分享、移动重命名整理、标签管理。',
    category: 'docs_storage',
    provider: '金山',
    icon: 'connector',
    iconImage: '/connector-icons/wps-office.webp',
    bgColor: '#dc2626',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://kdocs.cn/',
    docsUrl: 'https://kdocs.cn/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'create_doc', description: '创建文档' },
      { name: 'search_doc', description: '搜索文档' },
      { name: 'edit_doc', description: '编辑文档' },
    ]
  },
  {
    id: 'notion',
    name: 'Notion',
    displayName: 'Notion',
    description: '创建、搜索和管理 Notion 工作区。用自然语言读取页面、查询数据库、更新内容、整理知识库。',
    category: 'docs_storage',
    provider: 'Notion',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#111827',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://developers.notion.com/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'search_pages', description: '搜索页面' },
      { name: 'query_database', description: '查询数据库' },
      { name: 'update_page', description: '更新页面' },
    ]
  },
  {
    id: 'zhishixingqiu',
    name: '知识星球',
    displayName: '知识星球',
    description: '用自然语言管理知识星球：浏览星球内容、发帖评论、搜索主题、回答问题、管理笔记、查看用户信息。',
    category: 'docs_storage',
    provider: '知识星球',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#10b981',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://www.zsxq.com/',
    docsUrl: 'https://www.zsxq.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'list_posts', description: '浏览帖子' },
      { name: 'search_topic', description: '搜索主题' },
      { name: 'create_post', description: '发布内容' },
    ]
  },

  // ===== 会议/协作 =====
  {
    id: 'tencent_meeting',
    name: '腾讯会议',
    displayName: '腾讯会议',
    description: '通过命令行创建、查询和管理腾讯会议。支持快速发起会议、查看日程安排、管理参会人员。',
    category: 'collaboration',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://meeting.tencent.com/',
    docsUrl: 'https://cloud.tencent.com/product/tcmeeting',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'create_meeting', description: '创建会议' },
      { name: 'query_meeting', description: '查询会议' },
      { name: 'manage_participants', description: '管理参会人' },
    ]
  },
  {
    id: 'wecom',
    name: '企业微信',
    displayName: '企业微信',
    description: '企业微信 10 人及以下企业支持消息、文档、日程、会议、待办等MCP能力；10 人以上企业仅支持创建、读取文档和智能表格。',
    category: 'collaboration',
    provider: '企业微信',
    icon: 'connector',
    iconImage: '/connector-icons/wecom.png',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://work.weixin.qq.com/',
    docsUrl: 'https://developer.work.weixin.qq.com/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'send_message', description: '发送消息' },
      { name: 'create_doc', description: '创建文档' },
      { name: 'calendar', description: '日程管理' },
    ]
  },

  // ===== 问卷/调研 =====
  {
    id: 'tencent_wenjuan',
    name: '腾讯问卷',
    displayName: '腾讯问卷',
    description: '创建、管理和分析腾讯问卷。用自然语言快速生成问卷、查看回收数据、设置题目逻辑。',
    category: 'research',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#10b981',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://wj.qq.com/',
    docsUrl: 'https://wj.qq.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'create_survey', description: '创建问卷' },
      { name: 'analyze_responses', description: '分析回收数据' },
    ]
  },

  // ===== 研发管理 =====
  {
    id: 'tapd',
    name: 'TAPD',
    displayName: 'TAPD',
    description: '管理需求、缺陷、任务和迭代。查询项目进度、拆分需求、流转状态、填写工时，覆盖需求到发布的研发全生命周期。',
    category: 'dev_tools',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.tapd.cn/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'create_story', description: '创建需求' },
      { name: 'query_bug', description: '查询缺陷' },
      { name: 'update_status', description: '更新状态' },
    ]
  },
  {
    id: 'cnb',
    name: 'CNB',
    displayName: 'CNB',
    description: '通过自然语言管理 CNB 平台：仓库、Issue、PR、流水线、制品库等操作。',
    category: 'dev_tools',
    provider: 'CNB',
    icon: 'connector',
    bgColor: '#f97316',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'list_repos', description: '列出仓库' },
      { name: 'create_issue', description: '创建Issue' },
      { name: 'run_pipeline', description: '运行流水线' },
    ]
  },
  {
    id: 'github',
    name: 'GitHub',
    displayName: 'GitHub',
    description: '在 GitHub 上克隆、推送代码，查看和管理仓库与 Pull Request，用自然语言完成代码协作。',
    category: 'dev_tools',
    provider: 'GitHub',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#111827',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://github.com/login/oauth/authorize',
    docsUrl: 'https://docs.github.com/en/rest',
    priority: 'S',
    status: 'available',
    toolsPreview: [
      { name: 'list_repos', description: '列出仓库' },
      { name: 'create_pr', description: '创建PR' },
      { name: 'search_code', description: '搜索代码' },
    ]
  },

  // ===== 云服务 =====
  {
    id: 'tencent_cloudbase',
    name: '腾讯云 CloudBase',
    displayName: '腾讯云 CloudBase',
    description: '腾讯云开发 CloudBase 全栈开发、部署、调试与排障连接器。覆盖 Web 应用、微信小程序、uni-app、原生 App HTTP API、云函数、CloudRun、NoSQL/MySQL 数据库、云存储、静态托管等能力。',
    category: 'dev_tools',
    provider: '腾讯云',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://cloud.tencent.com/product/tcb',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'deploy_app', description: '部署应用' },
      { name: 'query_db', description: '查询数据库' },
      { name: 'manage_storage', description: '管理云存储' },
    ]
  },
  {
    id: 'edgeone_makers',
    name: 'EdgeOne Makers',
    displayName: 'EdgeOne Makers',
    description: '将项目部署到 EdgeOne Makers 并返回线上访问地址，支持全栈、云函数、AI Agent 等开发场景。',
    category: 'dev_tools',
    provider: '腾讯云',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://edgeone.ai/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'deploy_project', description: '部署项目' },
      { name: 'get_deploy_url', description: '获取访问地址' },
    ]
  },
  {
    id: 'bugly',
    name: 'Bugly 质量概览',
    displayName: 'Bugly 质量概览',
    description: '查看产品的质量概览，包括崩溃率、ANR 率、OOM 率、启动耗时等。',
    category: 'dev_tools',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://bugly.qq.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'crash_overview', description: '崩溃概览' },
      { name: 'anr_rate', description: 'ANR率' },
      { name: 'startup_time', description: '启动耗时' },
    ]
  },

  // ===== 云盘/存储 =====
  {
    id: 'weiyun',
    name: '微云',
    displayName: '微云',
    description: '查看、下载、删除微云文件，并且提供上传文件到微云、生成分享链接能力，帮你管理微云文件。',
    category: 'docs_storage',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://www.weiyun.com/',
    docsUrl: 'https://www.weiyun.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'list_files', description: '列出文件' },
      { name: 'upload_file', description: '上传文件' },
      { name: 'share_file', description: '生成分享链接' },
    ]
  },

  // ===== 法律 =====
  {
    id: 'beidafabao',
    name: '北大法宝',
    displayName: '北大法宝 · 法律智能检索',
    description: '语义（自然语言描述）+ 关键词（精确/模糊查询）双模式检索法规与案例，结果均带 pkulaw.com 原文链接，可追溯、可复核、可直接引用。',
    category: 'legal',
    provider: '北大法宝',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#dc2626',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.pkulaw.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'search_law', description: '法规检索' },
      { name: 'search_case', description: '案例检索' },
    ]
  },
  {
    id: 'qichacha',
    name: '企查查',
    displayName: '企查查',
    description: '查询和核实企业工商登记信息。支持股东结构、实际控制人、受益所有人、高管团队、对外投资、财务数据、年报及上市信息查询，用自然语言快速完成企业身份核验与背景调查。',
    category: 'legal',
    provider: '企查查',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.qcc.com/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'company_query', description: '企业查询' },
      { name: 'shareholder_query', description: '股东查询' },
      { name: 'financial_query', description: '财务查询' },
    ]
  },
  {
    id: 'tianyancha',
    name: '天眼查',
    displayName: '天眼查',
    description: '通过天眼查 MCP 查询多维度企业数据。支持工商登记、股东结构、司法风险、知识产权、董监高、经营数据等 160+ 项企业数据能力，用自然语言完成企业尽调与商业情报分析。',
    category: 'legal',
    provider: '天眼查',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.tianyancha.com/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'company_query', description: '企业查询' },
      { name: 'risk_query', description: '风险查询' },
      { name: 'ip_query', description: '知识产权查询' },
    ]
  },
  {
    id: 'huayuyuandian',
    name: '华宇元典法律数据',
    displayName: '华宇元典法律数据',
    description: '华宇元典法律数据为智能体提供法律法规、案例文书、企业信息 MCP 工具能力。',
    category: 'legal',
    provider: '华宇元典',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'law_search', description: '法规搜索' },
      { name: 'case_search', description: '案例搜索' },
    ]
  },
  {
    id: 'weikeyansuo',
    name: '威科先行',
    displayName: '威科先行',
    description: '威科先行依托全面、准确、及时更新的法规、案例等法律数据研发的MCP服务，支持语义检索、关键词检索等场景。',
    category: 'legal',
    provider: '威科先行',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#22c55e',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://law.wkinfo.com.cn/',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'law_search', description: '法规检索' },
      { name: 'case_search', description: '案例检索' },
    ]
  },
  {
    id: 'fayan',
    name: '法研',
    displayName: '法研 · 法律法规检索',
    description: '法研 · 法律法规检索，支持自然语言获取精准、现行有效的法规条文，将高质量、海量的法规知识库，无缝接入各类AI应用与工作流中。',
    category: 'legal',
    provider: '法研',
    icon: 'connector',
    bgColor: '#f97316',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'coming_soon',
    toolsPreview: [
      { name: 'law_search', description: '法规检索' },
    ]
  },

  // ===== 客服/销售 =====
  {
    id: 'tencent_qidian',
    name: '腾讯企点客服',
    displayName: '腾讯企点客服',
    description: '腾讯企点客服连接器：用自然语言处理工单（查询/创建/更新/状态变更）、查询坐席在线与实时接待、检索/拉取客户资料、拉取人工/大模型/文本机器人的会话记录和消息、查看客服实时监控。',
    category: 'marketing',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#8b5cf6',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://qidian.qq.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'ticket_query', description: '工单查询' },
      { name: 'ticket_create', description: '创建工单' },
      { name: 'customer_query', description: '客户查询' },
    ]
  },
  {
    id: 'xiaoshouyi',
    name: '销售易CRM',
    displayName: '销售易CRM',
    description: '用自然语言查客户、推商机、盘线索、领公海、写跟进，一句话打通销售工作闭环。',
    category: 'marketing',
    provider: '销售易',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.xiaoshouyi.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'customer_query', description: '客户查询' },
      { name: 'opportunity_query', description: '商机查询' },
      { name: 'create_followup', description: '创建跟进' },
    ]
  },
  {
    id: 'xiaoe_tong',
    name: '小鹅通',
    displayName: '小鹅通',
    description: '用自然语言管理小鹅通店铺：查询课程与学员，创建和编辑课程，查看订单，并查找或上传图片、音频、电子书和文档素材。',
    category: 'marketing',
    provider: '小鹅通',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.xiaoe-tech.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'course_query', description: '课程查询' },
      { name: 'order_query', description: '订单查询' },
      { name: 'create_course', description: '创建课程' },
    ]
  },
  {
    id: 'weisheng_qiweiguanjia',
    name: '微盛企微管家SCRM',
    displayName: '微盛企微管家SCRM',
    description: '查询或管理企业微信中的客户信息、客户标签、客户群、营销素材、活码、群发、跟进记录、联系人、商机、汇报、抽奖、客户日程、聊天记录等业务能力。',
    category: 'marketing',
    provider: '微盛',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'customer_query', description: '客户查询' },
      { name: 'tag_manage', description: '标签管理' },
      { name: 'group_send', description: '群发消息' },
    ]
  },
  {
    id: 'tencent_marketing',
    name: '腾讯营销投放',
    displayName: '腾讯营销投放',
    description: '腾讯营销投放 Skill，为大模型赋予广告投放管理能力：支持广告账户授权、广告/智投项目的创建与更新、广告数据查询与分析、推广内容资产管理，以及操作日志查询等完整的广告投放管理能力。',
    category: 'marketing',
    provider: '腾讯广告',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#ec4899',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://e.qq.com/',
    docsUrl: 'https://developers.e.qq.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'ad_create', description: '创建广告' },
      { name: 'ad_query', description: '查询广告数据' },
      { name: 'asset_manage', description: '素材管理' },
    ]
  },
  {
    id: 'canva',
    name: 'Canva可画',
    displayName: 'Canva可画',
    description: '让AI助手无缝调用Canva可画的设计能力，包括创建设计、编辑设计、管理素材和品牌资源、搜索资源库、导出设计以及添加评论等。',
    category: 'creative_core',
    provider: 'Canva',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#8b5cf6',
    textColor: '#ffffff',
    authMode: 'oauth',
    loginUrl: 'https://www.canva.cn/',
    docsUrl: 'https://www.canva.cn/developers/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'create_design', description: '创建设计' },
      { name: 'edit_design', description: '编辑设计' },
      { name: 'search_asset', description: '搜索素材' },
    ]
  },
  {
    id: 'mastergo',
    name: 'MasterGo 莫高设计',
    displayName: 'MasterGo 莫高设计',
    description: '连接 MasterGo 画布，让 AI 进行设计、修改、同步和获取 D2C 代码。',
    category: 'creative_core',
    provider: 'MasterGo',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://mastergo.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'create_design', description: '创建设计' },
      { name: 'get_d2c_code', description: '获取D2C代码' },
    ]
  },

  // ===== 地图/位置 =====
  {
    id: 'tencent_map',
    name: '腾讯地图',
    displayName: '腾讯地图',
    description: '接入腾讯地图各类位置服务，包括地点搜索、路线规划（驾车/公交/步行/骑行）、地址正逆解析、沿途搜索和天气查询等。',
    category: 'scene_reality',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/tencent-map.png',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://lbs.qq.com/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'place_search', description: '地点搜索' },
      { name: 'route_plan', description: '路线规划' },
      { name: 'geocoding', description: '地址解析' },
    ]
  },
  {
    id: 'quyu_dongcha',
    name: '区域洞察',
    displayName: '区域洞察',
    description: '区域洞察提供 POI 定位、围栏内 POI 查询与聚合能力。',
    category: 'scene_reality',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#f97316',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'poi_query', description: 'POI查询' },
      { name: 'fence_query', description: '围栏查询' },
    ]
  },

  // ===== 旅行 =====
  {
    id: 'ctrip_wendao',
    name: '携程问道',
    displayName: '携程问道',
    description: '通过携程问道 API 获取旅行规划与攻略。支持酒店查询、机票搜索、景点推荐、行程规划、美食住宿攻略。',
    category: 'travel',
    provider: '携程',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.ctrip.com/',
    priority: 'B',
    status: 'beta',
    toolsPreview: [
      { name: 'hotel_search', description: '酒店查询' },
      { name: 'flight_search', description: '机票搜索' },
      { name: 'attraction_search', description: '景点推荐' },
    ]
  },
  {
    id: 'tongchengxin',
    name: '同程心',
    displayName: '同程心',
    description: '同程程心可通过自然语言查询机票、火车票、酒店、景点、度假产品等旅行资源，支持火空联程、智能交通推荐、特价机票搜索、景区门票预订，以及完整行程规划，显著提升出行效率。',
    category: 'travel',
    provider: '同程',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#22c55e',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'flight_search', description: '机票查询' },
      { name: 'hotel_search', description: '酒店查询' },
      { name: 'trip_plan', description: '行程规划' },
    ]
  },

  // ===== 企业服务 =====
  {
    id: 'fubangshou',
    name: '福帮手',
    displayName: '福帮手',
    description: '福帮手人机协同连接器：面向 WorkBuddy 的身份识别、场景包查询、首值与继续使用记录、乐包状态确认和超级合伙人交接。',
    category: 'collaboration',
    provider: '腾讯',
    icon: 'connector',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'identity_verify', description: '身份识别' },
      { name: 'scene_query', description: '场景包查询' },
    ]
  },
  {
    id: 'agentkey',
    name: 'AgentKey',
    displayName: 'AgentKey',
    description: 'AgentKey 是 AI 助手获取可信工具和实时数据的能力市场。支持网页搜索、URL抓取、新闻、社交媒体、股票市场价格、电商产品数据、企业/公司数据、天气、地图和地理位置、旅行（航班/酒店等）等上百种能力。',
    category: 'research',
    provider: 'AgentKey',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#111827',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.agentkey.ai/',
    priority: 'A',
    status: 'available',
    toolsPreview: [
      { name: 'web_search', description: '网页搜索' },
      { name: 'web_fetch', description: 'URL抓取' },
      { name: 'stock_price', description: '股票价格' },
    ]
  },
  {
    id: 'qixinhuiyan',
    name: '启信慧眼',
    displayName: '启信慧眼',
    description: '通过启信慧眼 MCP 接入企业全景数据能力，支持用户用自然语言完成企业搜索、工商画像、风险识别、经营动态、知识产权等商业情报分析。',
    category: 'legal',
    provider: '启信慧眼',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#2563eb',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'company_search', description: '企业搜索' },
      { name: 'risk_analysis', description: '风险识别' },
    ]
  },

  // ===== 其他 =====
  {
    id: 'zhuiya',
    name: '智慧芽专利&文献融合检索',
    displayName: '智慧芽专利&文献融合检索',
    description: '在智慧芽全球专利数据库和文献库中进行融合检索，支持自然语言、语义搜索、关键词检索和多维过滤，并获取专利或文献信息。',
    category: 'research',
    provider: '智慧芽',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#10b981',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.zhihuiya.com/',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'patent_search', description: '专利检索' },
      { name: 'literature_search', description: '文献检索' },
    ]
  },
  {
    id: 'tencent_health',
    name: '腾讯健康NGES',
    displayName: '腾讯健康NGES',
    description: '腾讯健康NGES MCP服务，支持智能问答和合规审核等功能。',
    category: 'health',
    provider: '腾讯',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#22c55e',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'health_qa', description: '健康问答' },
      { name: 'compliance_check', description: '合规审核' },
    ]
  },
  {
    id: 'sunflower_remote',
    name: '向日葵远程控制',
    displayName: '向日葵远程控制',
    description: '通过命令行管理远端设备，实时监测在线状态、秒级发起远程控制、快速传输文件及远程截屏。零部署、免更新，轻松实现智能批量运维。',
    category: 'dev_tools',
    provider: '向日葵',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#ec4899',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://sunlogin.oray.com/',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'device_status', description: '设备状态' },
      { name: 'remote_control', description: '远程控制' },
      { name: 'file_transfer', description: '文件传输' },
    ]
  },
  {
    id: 'qingliu',
    name: '轻流',
    displayName: '轻流',
    description: '轻流无代码平台连接器。通过自然语言创建应用、管理表单数据、处理审批流程、查询和导出数据，一站式连接轻流全部能力。',
    category: 'collaboration',
    provider: '轻流',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    docsUrl: 'https://www.qingflow.com/',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'create_app', description: '创建应用' },
      { name: 'form_manage', description: '表单管理' },
      { name: 'approval_manage', description: '审批流程' },
    ]
  },
  {
    id: 'zhongxingxinyun',
    name: '中兴新云AI智报',
    displayName: '中兴新云AI智报',
    description: '财务云 AI 报销助手：用自然语言完成报销申请、发票查询识别、报销单查询与费用审批等操作。',
    category: 'collaboration',
    provider: '中兴新云',
    icon: 'connector',
    iconImage: '/connector-icons/karna-connector.svg',
    bgColor: '#0ea5e9',
    textColor: '#ffffff',
    authMode: 'api_key',
    priority: 'C',
    status: 'beta',
    toolsPreview: [
      { name: 'expense_create', description: '创建报销单' },
      { name: 'invoice_query', description: '发票查询' },
      { name: 'expense_approval', description: '费用审批' },
    ]
  },
]

// Only entries with a reviewed, locally packaged brand asset are exposed in
// the release catalog.  The larger upstream candidate list remains private to
// development until its official service, docs and connection path have been
// verified; Karna never pads the catalog with pretend-available connectors.
const VERIFIED_RELEASE_MCPS = new Set([
  'tencent_docs',
  'feishu',
  'dingtalk',
  'wps_docs',
  'wecom',
  'tencent_map'
])

export const BUILT_IN_MCPS: BuiltInMcp[] = MCP_CATALOG_CANDIDATES.filter(mcp => VERIFIED_RELEASE_MCPS.has(mcp.id))

export const MCP_CATEGORIES = [
  { id: 'all', label: '全部' },
  { id: 'collaboration', label: '协作办公' },
  { id: 'docs_storage', label: '文档与网盘' },
  { id: 'finance', label: '金融财经' },
  { id: 'legal', label: '法律合规' },
  { id: 'dev_tools', label: '开发工具' },
  { id: 'marketing', label: '营销增长' },
  { id: 'research', label: '研究资料' },
  { id: 'creative_core', label: '创作设计' },
  { id: 'health', label: '健康医疗' },
  { id: 'travel', label: '旅行出行' },
  { id: 'scene_reality', label: '场景现实' },
]
