'use strict'

const DEFAULT_CONFIG = {
  display: { language: 'zh', skin: 'karna', show_reasoning: true },
  models: { default: 'gpt-4o', auxiliary: [] },
  // 0 means auto-detect. Positive values are intentional user overrides.
  model_context_length: 0,
  fallback_providers: [],
  timezone: 'Asia/Shanghai',
  agent: {
    image_input_mode: 'auto',
    max_turns: 20,
    api_max_retries: 3,
    service_tier: 'normal',
    tool_use_enforcement: 'auto',
    reasoning_effort: 'medium'
  },
  terminal: {
    cwd: 'D:\\Agent',
    persistent_shell: true,
    env_passthrough: [],
    backend: 'local',
    timeout: 120,
    docker_image: '',
    singularity_image: '',
    modal_image: '',
    daytona_image: ''
  },
  code_execution: { mode: 'local' },
  file_read_max_chars: 20000,
  approvals: { mode: 'on-request', timeout: 60, mcp_reload_confirm: true },
  command_allowlist: [],
  security: { redact_secrets: true, allow_private_urls: false },
  browser: { allow_private_urls: false, auto_local_for_private_urls: true },
  checkpoints: { enabled: true, max_snapshots: 10 },
  memory: {
    memory_enabled: true,
    user_profile_enabled: true,
    memory_char_limit: 12000,
    user_char_limit: 4000,
    provider: ''
  },
  context: { engine: 'auto' },
  compression: { enabled: true, threshold: 0.8, target_ratio: 0.5, protect_last_n: 6 },
  tts: {
    provider: 'edge',
    edge: { voice: 'zh-CN-XiaoxiaoNeural' },
    openai: { model: 'gpt-4o-mini-tts', voice: 'alloy' },
    elevenlabs: { voice_id: '', model_id: '' },
    xai: { voice_id: '', language: 'zh' },
    minimax: { model: '', voice_id: '' },
    mistral: { model: '', voice_id: '' },
    gemini: { model: '', voice: '' },
    neutts: { model: '', device: 'auto' },
    kittentts: { model: '', voice: '' },
    piper: { voice: '' }
  },
  stt: {
    enabled: false,
    provider: 'local',
    local: { model: 'base', language: 'zh' },
    openai: { model: 'whisper-1' },
    groq: { model: 'whisper-large-v3' },
    mistral: { model: '' },
    elevenlabs: { model_id: '', language_code: 'zh', tag_audio_events: false, diarize: false }
  },
  voice: { auto_tts: false, record_key: 'Ctrl+Shift+Space', max_recording_seconds: 60 },
  toolsets: [],
  tool_output: { max_bytes: 200000, max_lines: 2000, max_line_length: 2000 },
  delegation: {
    model: '',
    provider: '',
    max_iterations: 5,
    max_concurrent_children: 2,
    child_timeout_seconds: 600,
    reasoning_effort: 'medium'
  },
  updates: { non_interactive_local_changes: false },
  tools: { enabled: [] },
  behavior: { autoCompact: true, maxTokens: 8192 }
}

const configField = (type, description, options) => ({
  type,
  description,
  ...(options ? { options } : {})
})

const CONFIG_SCHEMA = {
  fields: {
    model_context_length: configField('number', 'Maximum model context length.'),
    fallback_providers: configField('list', 'Fallback providers, separated by commas.'),
    timezone: configField('string', 'Timezone used by the assistant.'),
    'display.show_reasoning': configField('boolean', 'Show reasoning/status details in chat.'),
    'agent.image_input_mode': configField('select', 'How image input is handled.', ['auto', 'always', 'never']),
    'terminal.cwd': configField('string', 'Default working directory.'),
    'code_execution.mode': configField('select', 'Code execution mode.', ['local', 'sandbox']),
    'terminal.persistent_shell': configField('boolean', 'Keep terminal sessions alive.'),
    'terminal.env_passthrough': configField('list', 'Environment variables to pass through.'),
    file_read_max_chars: configField('number', 'Maximum characters to read from a file.'),
    'approvals.mode': configField('select', 'Command approval mode.', ['never', 'on-request', 'always']),
    'approvals.timeout': configField('number', 'Approval timeout in seconds.'),
    'approvals.mcp_reload_confirm': configField('boolean', 'Confirm before reloading MCP tools.'),
    command_allowlist: configField('list', 'Always-allowed commands.'),
    'security.redact_secrets': configField('boolean', 'Redact secrets in logs and UI.'),
    'security.allow_private_urls': configField('boolean', 'Allow private network URLs.'),
    'browser.allow_private_urls': configField('boolean', 'Allow browser access to private URLs.'),
    'browser.auto_local_for_private_urls': configField('boolean', 'Automatically treat private URLs as local.'),
    'checkpoints.enabled': configField('boolean', 'Enable workspace checkpoints.'),
    'memory.memory_enabled': configField('boolean', 'Enable memory.'),
    'memory.user_profile_enabled': configField('boolean', 'Enable user profile memory.'),
    'memory.memory_char_limit': configField('number', 'Memory character limit.'),
    'memory.user_char_limit': configField('number', 'User profile character limit.'),
    'memory.provider': configField('select', 'Memory provider.', ['', 'local']),
    'context.engine': configField('select', 'Context engine.', ['auto', 'basic']),
    'compression.enabled': configField('boolean', 'Enable context compression.'),
    'compression.threshold': configField('number', 'Compression threshold.'),
    'compression.target_ratio': configField('number', 'Compression target ratio.'),
    'compression.protect_last_n': configField('number', 'Recent turns protected from compression.'),
    'tts.provider': configField('select', 'Text-to-speech provider.', ['edge', 'openai', 'elevenlabs', 'xai', 'minimax', 'mistral', 'gemini', 'neutts', 'kittentts', 'piper']),
    'stt.enabled': configField('boolean', 'Enable speech-to-text.'),
    'stt.provider': configField('select', 'Speech-to-text provider.', ['local', 'openai', 'groq', 'mistral', 'elevenlabs']),
    'voice.auto_tts': configField('boolean', 'Automatically speak assistant responses.'),
    'tts.edge.voice': configField('string', 'Edge TTS voice.'),
    'tts.openai.model': configField('string', 'OpenAI TTS model.'),
    'tts.openai.voice': configField('string', 'OpenAI TTS voice.'),
    'tts.elevenlabs.voice_id': configField('string', 'ElevenLabs voice ID.'),
    'tts.elevenlabs.model_id': configField('string', 'ElevenLabs model ID.'),
    'tts.xai.voice_id': configField('string', 'xAI voice ID.'),
    'tts.xai.language': configField('string', 'xAI language.'),
    'tts.minimax.model': configField('string', 'MiniMax TTS model.'),
    'tts.minimax.voice_id': configField('string', 'MiniMax voice ID.'),
    'tts.mistral.model': configField('string', 'Mistral TTS model.'),
    'tts.mistral.voice_id': configField('string', 'Mistral voice ID.'),
    'tts.gemini.model': configField('string', 'Gemini TTS model.'),
    'tts.gemini.voice': configField('string', 'Gemini TTS voice.'),
    'tts.neutts.model': configField('string', 'NeuTTS model.'),
    'tts.neutts.device': configField('string', 'NeuTTS device.'),
    'tts.kittentts.model': configField('string', 'KittenTTS model.'),
    'tts.kittentts.voice': configField('string', 'KittenTTS voice.'),
    'tts.piper.voice': configField('string', 'Piper voice.'),
    'stt.local.model': configField('string', 'Local STT model.'),
    'stt.local.language': configField('string', 'Local STT language.'),
    'stt.openai.model': configField('string', 'OpenAI STT model.'),
    'stt.groq.model': configField('string', 'Groq STT model.'),
    'stt.mistral.model': configField('string', 'Mistral STT model.'),
    'stt.elevenlabs.model_id': configField('string', 'ElevenLabs STT model ID.'),
    'stt.elevenlabs.language_code': configField('string', 'ElevenLabs language code.'),
    'stt.elevenlabs.tag_audio_events': configField('boolean', 'Tag audio events.'),
    'stt.elevenlabs.diarize': configField('boolean', 'Speaker diarization.'),
    'voice.record_key': configField('string', 'Voice recording shortcut.'),
    'voice.max_recording_seconds': configField('number', 'Maximum recording seconds.'),
    toolsets: configField('list', 'Enabled toolsets.'),
    'terminal.backend': configField('select', 'Terminal backend.', ['local', 'pty']),
    'terminal.timeout': configField('number', 'Terminal command timeout.'),
    'terminal.docker_image': configField('string', 'Docker image.'),
    'terminal.singularity_image': configField('string', 'Singularity image.'),
    'terminal.modal_image': configField('string', 'Modal image.'),
    'terminal.daytona_image': configField('string', 'Daytona image.'),
    'tool_output.max_bytes': configField('number', 'Maximum tool output bytes.'),
    'tool_output.max_lines': configField('number', 'Maximum tool output lines.'),
    'tool_output.max_line_length': configField('number', 'Maximum tool output line length.'),
    'checkpoints.max_snapshots': configField('number', 'Maximum checkpoint snapshots.'),
    'agent.max_turns': configField('number', 'Maximum agent turns.'),
    'agent.api_max_retries': configField('number', 'Maximum API retries.'),
    'agent.service_tier': configField('select', 'Service tier.', ['normal', 'fast']),
    'agent.tool_use_enforcement': configField('select', 'Tool-use enforcement.', ['auto', 'strict', 'none']),
    'delegation.model': configField('string', 'Delegation model.'),
    'delegation.provider': configField('string', 'Delegation provider.'),
    'delegation.max_iterations': configField('number', 'Maximum delegation iterations.'),
    'delegation.max_concurrent_children': configField('number', 'Maximum child agents.'),
    'delegation.child_timeout_seconds': configField('number', 'Child timeout seconds.'),
    'delegation.reasoning_effort': configField('select', 'Delegation reasoning effort.', ['none', 'minimal', 'low', 'medium', 'high', 'xhigh']),
    'updates.non_interactive_local_changes': configField('boolean', 'Allow non-interactive update with local changes.')
  },
  sections: []
}

const createDefaultConfig = () => JSON.parse(JSON.stringify(DEFAULT_CONFIG))

module.exports = { CONFIG_SCHEMA, createDefaultConfig }

