package com.karna.android.core.designsystem

import androidx.compose.ui.graphics.Color

data class ColorFamily(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val success: Color,
    val warning: Color,
    val info: Color
)

val LightColorFamily = ColorFamily(
    primary = Color(0xFF6B8E7B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD7E8DC),
    onPrimaryContainer = Color(0xFF1A3C2A),
    secondary = Color(0xFF8B7E9C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8E0EF),
    onSecondaryContainer = Color(0xFF2B2338),
    tertiary = Color(0xFF9C8B7E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFEFE5DC),
    onTertiaryContainer = Color(0xFF382B23),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFAF9F7),
    onBackground = Color(0xFF1A1C19),
    surface = Color(0xFFFAF9F7),
    onSurface = Color(0xFF1A1C19),
    surfaceVariant = Color(0xFFE4E6E2),
    onSurfaceVariant = Color(0xFF434843),
    outline = Color(0xFF737972),
    outlineVariant = Color(0xFFC4C7C1),
    success = Color(0xFF4A7C59),
    warning = Color(0xFF8B6914),
    info = Color(0xFF4A6B8C)
)

val DarkColorFamily = ColorFamily(
    primary = Color(0xFF9BB4A7),
    onPrimary = Color(0xFF1A3C2A),
    primaryContainer = Color(0xFF2A4D3B),
    onPrimaryContainer = Color(0xFFD7E8DC),
    secondary = Color(0xFFB8ACC9),
    onSecondary = Color(0xFF2B2338),
    secondaryContainer = Color(0xFF3C334F),
    onSecondaryContainer = Color(0xFFE8E0EF),
    tertiary = Color(0xFFC9B8AB),
    onTertiary = Color(0xFF382B23),
    tertiaryContainer = Color(0xFF4D3E33),
    onTertiaryContainer = Color(0xFFEFE5DC),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1C19),
    onBackground = Color(0xFFE2E3DE),
    surface = Color(0xFF1A1C19),
    onSurface = Color(0xFFE2E3DE),
    surfaceVariant = Color(0xFF434843),
    onSurfaceVariant = Color(0xFFC4C7C1),
    outline = Color(0xFF8D938B),
    outlineVariant = Color(0xFF434843),
    success = Color(0xFF7FB08C),
    warning = Color(0xFFD4A84B),
    info = Color(0xFF7FA3C4)
)
