import type { DocumentPreset } from './types'

export const DOCUMENT_PRESETS: DocumentPreset[] = [
  { id: 'novel-outline', label: '故事大纲', description: '三幕结构故事大纲模板', documentType: 'outline', defaultPath: '规划/故事大纲.md', kind: 'file' },
  { id: 'character-bible', label: '人物设定', description: '主要人物档案模板', documentType: 'knowledge_asset', defaultPath: '设定/人物设定.md', kind: 'file' },
  { id: 'worldbuilding', label: '世界观设定', description: '世界观和规则设定', documentType: 'knowledge_asset', defaultPath: '设定/世界观.md', kind: 'file' },
  { id: 'timeline', label: '时间轴', description: '故事时间线模板', documentType: 'knowledge_asset', defaultPath: '设定/时间轴.md', kind: 'file' },
  { id: 'manuscript-dir', label: '正文章节', description: '正文写作目录', documentType: 'narrative_prose', defaultPath: '正文/', kind: 'directory' },
  { id: 'research-dir', label: '研究资料', description: '资料收集和研究笔记', documentType: 'research_material', defaultPath: '资料/', kind: 'directory' },
  { id: 'revisions-dir', label: '修订版本', description: '修订稿和版本对比', documentType: 'revision_artifact', defaultPath: '修订/', kind: 'directory' },
  { id: 'screenplay-outline', label: '剧本大纲', description: '三幕结构剧本大纲', documentType: 'outline', defaultPath: '规划/剧本大纲.md', kind: 'file' },
  { id: 'character-dossier', label: '人物小传', description: '角色人物小传', documentType: 'knowledge_asset', defaultPath: '人物/人物小传.md', kind: 'file' },
  { id: 'scene-list', label: '分场大纲', description: '场次列表和节拍表', documentType: 'outline', defaultPath: '规划/分场大纲.md', kind: 'file' },
  { id: 'scenes-dir', label: '场景剧本', description: '分场景剧本目录', documentType: 'script_dialogue', defaultPath: '剧本/场景/', kind: 'directory' },
  { id: 'story-bible', label: '剧集圣经', description: 'Series Bible 剧集设定', documentType: 'knowledge_asset', defaultPath: '设定/剧集圣经.md', kind: 'file' },
  { id: 'game-world', label: '世界观设定', description: '游戏世界和阵营设定', documentType: 'knowledge_asset', defaultPath: '设定/世界观.md', kind: 'file' },
  { id: 'main-quest', label: '主线剧情', description: '游戏主线剧情脚本', documentType: 'interactive_narrative', defaultPath: '剧情/主线.md', kind: 'file' },
  { id: 'character-dialogue', label: 'NPC对话', description: 'NPC 对话和语音台词', documentType: 'interactive_narrative', defaultPath: '对话/NPC/', kind: 'directory' },
  { id: 'quest-text', label: '任务文本', description: '任务描述和系统文本', documentType: 'interactive_narrative', defaultPath: '系统/任务文本.md', kind: 'file' },
  { id: 'brand-story', label: '品牌故事', description: '品牌定位和品牌故事', documentType: 'marketing_copy', defaultPath: '品牌/品牌故事.md', kind: 'file' },
  { id: 'brand-voice', label: '品牌语调', description: '品牌语调和命名规范', documentType: 'knowledge_asset', defaultPath: '品牌/语调指南.md', kind: 'file' },
  { id: 'slogan', label: 'Slogan 方案', description: '核心传播语和Tagline', documentType: 'marketing_copy', defaultPath: '品牌/Slogan.md', kind: 'file' },
  { id: 'ad-campaign', label: '广告文案', description: '广告创意和文案方案', documentType: 'marketing_copy', defaultPath: '广告/广告文案.md', kind: 'file' },
  { id: 'product-detail', label: '商品详情页', description: '电商商品详情文案', documentType: 'marketing_copy', defaultPath: '电商/商品详情.md', kind: 'file' },
  { id: 'content-calendar', label: '内容排期', description: '社交媒体内容日历', documentType: 'outline', defaultPath: '运营/内容排期.md', kind: 'file' },
  { id: 'seo-articles-dir', label: 'SEO文章', description: 'SEO优化文章目录', documentType: 'informational_article', defaultPath: '内容/SEO/', kind: 'directory' },
  { id: 'whitepaper', label: '白皮书', description: '行业白皮书或电子书', documentType: 'informational_article', defaultPath: '内容/白皮书.md', kind: 'file' },
  { id: 'news-article', label: '新闻报道', description: '新闻稿件模板', documentType: 'informational_article', defaultPath: '新闻/新闻稿.md', kind: 'file' },
  { id: 'press-release', label: '新闻通稿', description: '媒体通稿和发布会稿', documentType: 'informational_article', defaultPath: '公关/新闻通稿.md', kind: 'file' },
  { id: 'manuscript-book', label: '图书书稿', description: '图书正文稿件', documentType: 'narrative_prose', defaultPath: '书稿/正文/', kind: 'directory' },
  { id: 'book-proposal', label: '选题报告', description: '图书选题申报材料', documentType: 'structured_business_doc', defaultPath: '出版/选题报告.md', kind: 'file' },
  { id: 'academic-paper', label: '学术论文', description: '标准学术论文模板', documentType: 'argumentative_document', defaultPath: '论文/正文.md', kind: 'file' },
  { id: 'literature-review', label: '文献综述', description: '文献综述写作模板', documentType: 'argumentative_document', defaultPath: '论文/文献综述.md', kind: 'file' },
  { id: 'research-plan', label: '研究方案', description: '研究计划和实验方案', documentType: 'outline', defaultPath: '研究/研究方案.md', kind: 'file' },
  { id: 'grant-application', label: '基金申请书', description: '基金项目申请模板', documentType: 'structured_business_doc', defaultPath: '申请/基金申请书.md', kind: 'file' },
  { id: 'business-plan-doc', label: '商业计划书', description: '完整商业计划书模板', documentType: 'structured_business_doc', defaultPath: '商业/商业计划书.md', kind: 'file' },
  { id: 'prd', label: '产品需求文档', description: 'PRD 产品需求文档', documentType: 'structured_business_doc', defaultPath: '产品/PRD.md', kind: 'file' },
  { id: 'project-proposal', label: '项目方案', description: '项目建议书和方案', documentType: 'structured_business_doc', defaultPath: '项目/项目方案.md', kind: 'file' },
  { id: 'bid-proposal', label: '投标书', description: '投标文件模板', documentType: 'structured_business_doc', defaultPath: '投标/投标书.md', kind: 'file' },
  { id: 'meeting-minutes', label: '会议纪要', description: '会议记录模板', documentType: 'review_feedback', defaultPath: '会议/会议纪要.md', kind: 'file' },
  { id: 'weekly-report', label: '周报', description: '周工作总结模板', documentType: 'review_feedback', defaultPath: '汇报/周报.md', kind: 'file' },
  { id: 'sales-pitch', label: '销售提案', description: '销售提案和Pitch', documentType: 'marketing_copy', defaultPath: '销售/提案书.md', kind: 'file' },
  { id: 'contract-template', label: '合同模板', description: '标准合同模板', documentType: 'regulated_document', defaultPath: '法律/合同.md', kind: 'file' },
  { id: 'legal-opinion', label: '法律意见书', description: '法律意见模板', documentType: 'regulated_document', defaultPath: '法律/法律意见书.md', kind: 'file' },
  { id: 'privacy-policy', label: '隐私政策', description: '隐私政策模板', documentType: 'regulated_document', defaultPath: '合规/隐私政策.md', kind: 'file' },
  { id: 'government-notice', label: '通知通告', description: '政务通知公告', documentType: 'regulated_document', defaultPath: '公文/通知.md', kind: 'file' },
  { id: 'government-report', label: '工作报告', description: '政府/企业工作报告', documentType: 'structured_business_doc', defaultPath: '汇报/工作报告.md', kind: 'file' },
  { id: 'readme', label: '项目 README', description: '项目说明文档', documentType: 'technical_document', defaultPath: 'README.md', kind: 'file' },
  { id: 'api-docs', label: 'API 文档', description: 'API 接口文档', documentType: 'technical_document', defaultPath: 'docs/api.md', kind: 'file' },
  { id: 'architecture-doc', label: '架构设计', description: '系统架构设计文档', documentType: 'technical_document', defaultPath: 'docs/architecture.md', kind: 'file' },
  { id: 'tech-spec', label: '技术方案', description: '技术方案和设计文档', documentType: 'technical_document', defaultPath: 'docs/technical-design.md', kind: 'file' },
  { id: 'user-manual', label: '用户手册', description: '用户使用手册', documentType: 'technical_document', defaultPath: 'docs/user-manual.md', kind: 'file' },
  { id: 'test-plan', label: '测试计划', description: '测试计划和用例', documentType: 'technical_document', defaultPath: 'tests/test-plan.md', kind: 'file' },
  { id: 'release-notes', label: '版本说明', description: 'Release Notes / Changelog', documentType: 'revision_artifact', defaultPath: 'CHANGELOG.md', kind: 'file' },
  { id: 'wiki-home', label: 'Wiki 首页', description: '知识库首页和目录', documentType: 'knowledge_asset', defaultPath: 'wiki/Home.md', kind: 'file' },
  { id: 'glossary', label: '术语表', description: '术语和概念定义', documentType: 'knowledge_asset', defaultPath: 'wiki/术语表.md', kind: 'file' },
  { id: 'evidence-library', label: '证据库', description: '引用来源和证据档案', documentType: 'research_material', defaultPath: 'evidence/', kind: 'directory' },
  { id: 'soul-profile', label: 'Soul 档案', description: '风格和人格档案', documentType: 'knowledge_asset', defaultPath: 'soul/profile.md', kind: 'file' },
  { id: 'prompt-library', label: 'Prompt 库', description: '提示词模板库', documentType: 'knowledge_asset', defaultPath: 'prompts/', kind: 'directory' }
] as const
